apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-data
  namespace: cabflow
  labels:
    app: cabflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-data
  namespace: cabflow
  labels:
    app: cabflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
